language: dart
sudo: false
dart:
  - dev
  - stable
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test: --platform vm
    install_dartium: true
  - dartanalyzer
  - dartfmt
after_script: dart tool/run_coverage.dart
matrix:
  # Only run dartfmt checks with stable.
  exclude:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task: dartanalyzer
