name: kilobyte
description: >
  Cross-platform human-readable file size.
version: 0.2.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/kilobyte

environment:
  sdk: ">=2.0.0 <=3.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.5.2
