name: kilobyte
description: >
  A cross-platform human-readable file size library.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/kilobyte

environment:
  sdk: ">=1.22.0 <2.0.0"

dev_dependencies:
  test: ^0.12.20+12
