# https://dart.dev/tools/pub/pubspec

name: kilobyte
description: >
  Lightweight human-readable file size representations in Dart.

version: 0.3.0
environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  coverage: ^1.7.2
  oath: ^0.1.0
  test: ^1.25.3
