name: kilobyte
description: >
  Cross-platform human-readable file size.
version: 0.1.0+2
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/kilobyte

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=0.10.0 <2.0.0"

dev_dependencies:
  test: ^1.3.3
