name: check

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1.6.4
      - run: dart pub get
      - run: dart format --output none --set-exit-if-changed .
      - run: dart analyze
      - run: dart run coverage:test_with_coverage -- --reporter github
      - name: Upload Code Coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          file: coverage/lcov.info
